application/application/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import update_status

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comics.urls')),
    path('user/', include('users.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),

    path('check_online/', update_status, name='update_status')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]

application/apps/users/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

from .views import UserRegistration, UserLogin, UserProfile, EditProfile, activate_user


urlpatterns = [
    path('register/', UserRegistration.as_view(), name='user_registration'),
    path('auth/', UserLogin.as_view(), name='user_authentication'),
    path('logout/', login_required(LogoutView.as_view(next_page='/')), name='logout'),
    path('<int:pk>/', UserProfile.as_view(), name='user_profile'),
    path('edit-profile/', login_required(EditProfile.as_view()), name='edit_profile'),
    path('activate-user/<uidb64>/<token>', activate_user, name='activate')
    # path('<str:username>/', UserProfile.as_view(), name='user_profile')
]

application/apps/users/models.py
from PIL import Image
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.cache import cache
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.contrib.humanize.templatetags.humanize import naturaltime

from utils import upload_user_avatars_func
from .managers import CustomUserManager


class User(AbstractUser):

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(max_length=20, unique=False, null=False, blank=True)
    first_name = None
    last_name = None
    email = models.EmailField(unique=True, null=False)
    avatar = models.ImageField(upload_to=upload_user_avatars_func,
                               null=True,
                               blank=True,
                               validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
                               default=None)

    is_verified = models.BooleanField('Verified', default=False)
    last_online = models.DateTimeField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    @staticmethod
    def crop_center(pil_img, crop_width: int, crop_height: int) -> Image:
        img_width, img_height = pil_img.size
        return pil_img.crop(((img_width - crop_width) // 2,
                             (img_height - crop_height) // 2,
                             (img_width + crop_width) // 2,
                             (img_height + crop_height) // 2))

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            img = Image.open(self.avatar.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)

            img = self.crop_center(img, 120, 120)
            img.save(self.avatar.path)

    def avatar_url(self):
        if self.avatar:
            return mark_safe(f'<img src="{self.avatar.url}" width="auto" height="120">')

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class Profile(models.Model):
    """Profile user model"""

    SEX_USER_CHOICES = [
        (0, 'Male'),
        (1, 'Female')
    ]

    status = models.CharField(max_length=50, null=True, blank=True)
    sex = models.BooleanField(choices=SEX_USER_CHOICES, blank=True, null=True)
    birthday = models.DateTimeField(blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.first_name} {self.last_name} | {self.user}'

    class Meta:
        verbose_name = 'User profile'
        verbose_name_plural = 'Users profiles'


class UserTokens(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)

application/apps/users/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError

from .models import User, Profile


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email')


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = 'Email'
        self.fields['password'].label = 'Password'

    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        user = User.objects.filter(email=email).first()
        print(user.check_password(password))
        if (not user) or (not user.check_password(password)):
            raise forms.ValidationError('Email or password is wrong')

        return self.cleaned_data


class BaseUpdateForm(forms.ModelForm):

    def is_valid(self, *args, **kwargs):
        result = super().is_valid()
        for x in (self.fields if '__all__' in self.errors else self.errors):
            attrs = self.fields[x].widget.attrs
            attrs.update({'class': attrs.get('class', '') + ' ' + 'is-invalid'})
        return result


class UserUpdateForm(BaseUpdateForm):

    def clean_username(self):
        username = self.cleaned_data['username']

        if not username:
            raise forms.ValidationError('The user name cannot be empty')

        match = re.match('^[a-zA-Z0-9_]+$', username)

        if match is None:
            error_string = 'The username contains invalid characters. Only "a-z, A-Z, 0-9, _" is available.'
            raise forms.ValidationError(error_string)

        return username

    class Meta:
        model = User
        fields = ['username', 'avatar']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'textinput textInput form-control'})
        }


class ProfileUpdateForm(BaseUpdateForm):
    status = forms.Textarea()

    class Meta:
        model = Profile
        fields = ['status', 'sex', 'birthday', 'first_name', 'last_name']
        widgets = {
            'status': forms.TextInput(attrs={'class': 'textinput textInput form-control'}),
            'sex': forms.Select(attrs={'class': 'select form-control'}),
            'birthday': forms.TextInput(attrs={'class': 'textinput textInput form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'textinput textInput form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'textinput textInput form-control'}),
        }

application/apps/users/views.py
import random
import threading

from django import views
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

from comics.models import Comics
from .forms import CustomUserCreationForm, LoginForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile
from .utils import generate_token


User = get_user_model()
error_css_class = 'is-valid'


def activate_user(request, uidb64, token):

    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except Exception as e:
        user = None

    if user and generate_token.check_token(user, token):
        user.is_verified = True
        user.is_active = True
        user.save()

        messages.add_message(request, messages.SUCCESS, 'Email verified, you can login!')
        return redirect(reverse('user_authentication'))

    return render(request, 'users/activation-failed.html', {'user': user})


class EmailThread(threading.Thread):

    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self) -> None:
        self.email.send()


class UserRegistration(views.View):

    @staticmethod
    def generate_code():
        random.seed()
        return str(random.randint(100000, 999999))

    @staticmethod
    def send_activation_email(request, user):
        current_site = get_current_site(request)
        email_subject = 'Activate your account'
        email_body = render_to_string('users/activate.html', {
            'user': user,
            'domain': current_site,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': generate_token.make_token(user)
        })

        email = EmailMessage(
            subject=email_subject, body=email_body, from_email=settings.EMAIL_HOST_USER, to=[user.email]
        )
        EmailThread(email).start()

    @staticmethod
    def context(user_form):
        return {'user_form': user_form}

    def get(self, request, *args, **kwargs):
        user_form = CustomUserCreationForm()
        return render(request, 'users/registration.html', context=self.context(user_form))

    def post(self, request, *args, **kwargs):
        user_form = CustomUserCreationForm(request.POST or None)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.username = user_form.cleaned_data['username']
            new_user.email = user_form.cleaned_data['email']
            new_user.save()
            new_user.set_password(user_form.cleaned_data['password1'])
            new_user.save()

            self.send_activation_email(request, new_user)

            messages.add_message(request, messages.SUCCESS, 'To enter, you have to confirm your email. Check your email')

            return render(request, 'users/verificate_email.html')

        return render(request, 'users/registration.html', context=self.context(user_form))


class UserLogin(views.View):

    @staticmethod
    def context(user_form):
        return {'user_form': user_form}

    def get(self, request, *args, **kwargs):
        user_form = LoginForm()
        return render(request, 'users/authentication.html', context=self.context(user_form))

    def post(self, request, *args, **kwargs):
        user_form = LoginForm(request.POST or None)
        if user_form.is_valid():
            email = user_form.cleaned_data['email']
            password = user_form.cleaned_data['password']
            user = authenticate(email=email, password=password)

            if not user.is_verified:
                messages.add_message(request, messages.ERROR, 'Email is not verified, please check your email')
                return render(request, 'users/authentication.html', context=self.context(user_form))

            if user:
                if not Profile.objects.filter(user=user).exists():
                    Profile.objects.create(user=user)

                login(request, user)
                return redirect('main_page')

        return render(request, 'users/authentication.html', context=self.context(user_form))


class EditProfile(views.View):

    @staticmethod
    def context(user_form, profile_form):
        return {'user_form': user_form, 'profile_form': profile_form}

    def get(self, request, *args, **kwargs):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=Profile.objects.get(user=request.user))
        return render(request, 'users/user_edit_profile.html', context=self.context(user_form, profile_form))

    def post(self, request, *args, **kwargs):
        user_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=Profile.objects.get(user=request.user))
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user_profile', pk=request.user.pk)

        return render(request, 'users/user_edit_profile.html', context=self.context(user_form, profile_form))


class UserProfile(views.View):

    @staticmethod
    def count_all_views(comics):
        comics_views = 0
        for comic_book in comics:
            comics_views += comic_book.unique_views.count()
        return comics_views

    def get(self, request, pk, *args, **kwargs):
        user = get_object_or_404(User, pk=pk)
        user_profile = Profile.objects.get(user=user)

        comics = Comics.objects.prefetch_related('unique_views').filter(author=user)

        if not comics.exists():
            comics = None
            comics_count = 0
            comics_views = 0
        else:
            comics_count = comics.count()
            comics_views = self.count_all_views(comics)

        context = {
            'user': user,
            'user_profile': user_profile,
            'comics': comics,
            'comics_count': comics_count,
            'comics_views': comics_views
        }
        return render(request, 'users/user_profile.html', context=context)

application/apps/users/templates/users/activate.html
{% autoescape off %}

    Hi, {{ user.username }}!

    Please user the link below to verify your account.

    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

application/apps/users/templates/users/activation-failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

application/apps/users/templates/users/authentication.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Authentication | {{ block.super }}{% endblock title %}

{% block content %}
    <div class="container">
        <h3 class="mt-5 mb-5 text-center">Authentication</h3>
        <form method="post">
            {% csrf_token %}

            {{ user_form|crispy }}
            <button type="submit" class="btn btn-outline-primary">Sign in</button>
        </form>
    </div>
{% endblock content %}

application/apps/users/templates/users/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registration | {{ block.super }}{% endblock title %}

{% block content %}
    <div class="container">
        <h3 class="mt-5 mb-5 text-center">Registration</h3>
        <form method="post">
            {% csrf_token %}

            {{ user_form|crispy }}
            <button type="submit" class="btn btn-outline-primary">Registration</button>
        </form>
    </div>
{% endblock content %}

application/apps/users/templates/users/user_edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit profile | {{ block.super }}{% endblock title %}

{% block content %}
    <div class="container">
        <h3 class="mt-5 mb-5 text-center">Edit profile</h3>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_username" style="font-size: 1.3em;">Username</label>
                <div>
                    {{ user_form.username }}
                    {% if user_form.username.errors %}
                        {% for error in user_form.username.errors %}
                            <p class="invalid-f style="font-size: 1.3em;"eedback">
                                <strong>{{ error|escape }}</strong>
                            </p>
                        {% endfor %}
                    {% else %}
                        <small id="emailHelp" class="form-text text-muted">
                            The username may only contain "a-z, A-Z, 0-9, _"
                        </small>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_avatar" style="font-size: 1.3em;">Avatar</label>
                <div>
                    {{ user_form.avatar }}
                    {% if user_form.avatar.errors %}
                        <p id="error_1_id_avatar" class="invalid-feedback">
                            <strong>{{ user_form.avatar.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_status" style="font-size: 1.3em;">Status</label>
                <div>
                    {{ profile_form.status }}
                    {% if profile_form.status.errors %}
                        <p id="error_1_id_status" class="invalid-feedback">
                            <strong>{{ profile_form.status.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_sex" style="font-size: 1.3em;">Sex</label>
                <div>
                    {{ profile_form.sex }}
                    {% if profile_form.sex.errors %}
                        <p id="error_1_id_sex" class="invalid-feedback">
                            <strong>{{ profile_form.sex.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_birthday" style="font-size: 1.3em;">Birthday</label>
                <div>
                    {{ profile_form.birthday }}
                    {% if profile_form.birthday.errors %}
                        <p id="error_1_id_birthday" class="invalid-feedback">
                            <strong>{{ profile_form.birthday.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_first_name" style="font-size: 1.3em;">First name</label>
                <div>
                    {{ profile_form.first_name }}
                    {% if profile_form.first_name.errors %}
                        <p id="error_1_id_first_name" class="invalid-feedback">
                            <strong>{{ profile_form.first_name.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                <label for="id_last_name" style="font-size: 1.3em;">Last name</label>
                <div>
                    {{ profile_form.last_name }}
                    {% if profile_form.last_name.errors %}
                        <p id="error_1_id_last_name" class="invalid-feedback">
                            <strong>{{ profile_form.last_name.errors }}</strong>
                        </p>
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-outline-primary">Edit</button>
        </form>
    </div>
{% endblock content %}

application/apps/users/templates/users/verificate_email.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h3 class="mt-5 mb-5 text-center">Authentication</h3>
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% endif %}
    </div>
{% endblock content %}